=== Magecachaman/dog_daycare/dog_daycare.dtd
<!ELEMENT dog_daycare (owners+)>
<!ELEMENT owners (owner+)>
<!ELEMENT owner (ow_name,ow_dni,ow_contact,dogs)>
<!ELEMENT ow_name (#PCDATA)>
<!ELEMENT ow_dni (#PCDATA)>
<!ELEMENT ow_contact (email?,phone+)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT dogs (dog+)>
<!ELEMENT dog (dog_name,dog_age,dog_sex,dog_breed,dog_size,dog_weight,dog_height,medical_cond*,extras)>
<!ELEMENT dog_name (#PCDATA)>
<!ELEMENT dog_age (#PCDATA)>
<!ELEMENT dog_sex (#PCDATA)>
<!ELEMENT dog_breed (#PCDATA)>
<!ELEMENT dog_size (#PCDATA)>
<!ELEMENT dog_weight (#PCDATA)>
<!ELEMENT dog_height (#PCDATA)>
<!ELEMENT medical_cond (medical_cond_name?,medical_cond_treatment?)>
<!ELEMENT medical_cond_name (#PCDATA)>
<!ELEMENT medical_cond_treatment (#PCDATA)>
<!ELEMENT extras (ex_behavior,ex_chipnumber)>
<!ELEMENT ex_behavior (#PCDATA)>
<!ELEMENT ex_chipnumber (#PCDATA)>

=== Magecachaman/dog_daycare/dog_daycare.xml
<!DOCTYPE dog_daycare SYSTEM "dog_daycare.dtd">
<dog_daycare>
    <owners>
        <owner>
            <ow_name>Felipe Garc√≠a</ow_name>
            <ow_dni>12345678A</ow_dni>
            <ow_contact>
                <email></email>
                <phone>123456789</phone>
            </ow_contact>
            <dogs>
                <dog>
                    <dog_name>Billy</dog_name>
                    <dog_age>6</dog_age>
                    <dog_sex>Male</dog_sex>
                    <dog_breed>Shiba Inu</dog_breed>
                    <dog_size>Small/Medium</dog_size>
                    <dog_weight>10</dog_weight>
                    <dog_height>35</dog_height>
                    <medical_cond>
                        <medical_cond_name>None</medical_cond_name>
                        <medical_cond_treatment>None</medical_cond_treatment>
                    </medical_cond>
                    <extras>
                        <ex_behavior>Sociable</ex_behavior>
                        <ex_chipnumber>45678148B</ex_chipnumber>
                    </extras>
                </dog>
            </dogs>
        </owner>
    </owners>
</dog_daycare>
